name: Sync Repository Action
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: x-dr/sync-repo-to-gitee@master
      env:
          # 在 Settings->Secrets 配置 GITEE_KEY
          SSH_KEY: ${{ secrets.GITEE_KEY }}
      with:
          # 注意替换为你的 GitHub 源仓库地址
          github-repo: "git@github.com:veink-y/msgqywx.git"
          # 注意替换为你的 Gitee 目标仓库地址
          gitee-repo: "git@gitee.com:yhf2lj/msgqywx.git"
